mode: rule
mixed-port: 7890
ipv6: true
log-level: debug
unified-delay: true # 统一延迟
tcp-concurrent: true # TCP并发
geodata-mode: true # 使用 GeoIP.dat
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports:
      - 80
      - 8080-8880
    TLS:
      ports:
      - 443
      - 8443
    QUIC:
      ports:
      - 443
      - 8443
dns:
  enable: true
  ipv6: true
  prefer-h3: false
  use-hosts: true
  use-system-hosts: false
  respect-rules: false
  default-nameserver:
  - tls://223.5.5.5
  - tls://1.12.12.12
  proxy-server-nameserver:
  - tls://223.5.5.5
  - tls://1.12.12.12
  nameserver-policy:
    geosite:apple,cn:
    - tls://223.5.5.5
    - tls://1.12.12.12
  nameserver:
  - https://208.67.220.220/dns-query
  - https://9.9.9.12/dns-query
