mode: rule
mixed-port: 7890
ipv6: true
log-level: debug
unified-delay: true # 统一延迟
tcp-concurrent: true # TCP并发
geodata-mode: true # 使用 GeoIP.dat
# 外部控制 (API)
external-controller: 0.0.0.0:9090
# API 的访问密钥
secret: ""
# 外部用户界面
external-ui: ui
# 自定义外部用户界面下载地址
external-ui-url: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

# 嗅探器
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-dst-address: ["geoip:telegram"] #跳过嗅探目标IP
# DNS
dns:
  enable: true
  prefer-h3: false # DOH 优先使用 http/3
  use-hosts: true # 是否回应配置中的 hosts，默认 true
  use-system-hosts: true # 是否查询系统 hosts，默认 true
  respect-rules: false # dns 连接遵守路由规则，需配置 proxy-server-nameserver
  listen: 0.0.0.0:9853
  ipv6: true
  enhanced-mode: redir-host # 可选值 fake-ip/redir-host，默认redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: whitelist # blacklist | whitelist
  fake-ip-filter:
    - "geosite:google,bing,github,gfw"
  default-nameserver:
    - 'quic://223.5.5.5'
    - 'tls://1.12.12.12'
  proxy-server-nameserver:
    - 'https://223.5.5.5/dns-query'
    - 'https://1.12.12.12/dns-query'
  nameserver-policy:
    "geosite:private,apple,cn":
      - 'quic://223.5.5.5'
      - 'tls://1.12.12.12'
  nameserver:
    - 'https://1.0.0.1/dns-query'
    - 'https://94.140.14.14/dns-query'
    - 'https://dns.flymc.cc/dns-query'

    

